# Generated by Django 3.0.5 on 2021-06-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='ingestion',
            field=models.CharField(choices=[('Завтрак', 'Breakfast'), ('Обед', 'Lunch'), ('Ужин', 'Dinner')], default='Обед', max_length=10, unique=True, verbose_name='Время приема'),
        ),
    ]
