# Generated by Django 3.0.5 on 2021-06-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_auto_20210608_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='ingestion',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин')], default='lunch', max_length=10, unique=True, verbose_name='Время приема'),
        ),
    ]
